
services:
  alphabakery-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: "alphabakery-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - alphabakery-mysql-data:/var/lib/mysql

  alphabakery-redis:
    image: "redis:latest"
    container_name: "alphabakery-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - alphabakery-redis-data:/data

volumes:
  alphabakery-redis-data:
  alphabakery-mysql-data: